list(
  APPEND
  LV_EDITOR_PROJECT_SOURCES
  ${CMAKE_CURRENT_LIST_DIR}/components/activity_summary_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/app_header_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/card_container_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/face_thumbnail_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/launcher_icon_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/layout_block_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/layout_option_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/metric_full_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/metric_half_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/page_dots_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/picker_header_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/picker_list_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/tile_full_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/tile_grid_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/tile_half_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/tile_quarter_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/body_20_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/clock_80_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/icons_20_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/icons_44_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/metric_56_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/title_24_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/value_36_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/hour_1_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/hour_2_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/hour_3_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/hour_4_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/hour_5_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/hour_6_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/hour_7_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/hour_8_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/hour_9_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/hour_10_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/hour_11_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/hour_12_data.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_app_placeholder_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_control_center_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_face_picker_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_flashlight_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_launcher_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_layout_picker_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_picker_full_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_picker_half_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_picker_quarter_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_product_activity_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_product_daily_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_product_health_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_product_launcher_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_product_placeholder_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_settings_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_stopwatch_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_tile_activity_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_tile_full_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_tile_heart_rate_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_tile_system_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_watchface_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_watchface_simple_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/wristflow_ui_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/wristflow_ui.c)