from building import *

sources = Glob('*.c') + Glob('screens/*.c') + Glob('components/*.c')
image_sources = [source for source in Glob('images/*_data.c')
                 if not str(source).replace('\\', '/').endswith('/hour_seven_data.c')]
sources += Glob('fonts/*_data.c') + image_sources
objs = DefineGroup('WristFlowGeneratedUi', sources, depend=[''],
                   CPPPATH=[GetCurrentDir()],
                   CPPDEFINES=['LV_LVGL_H_INCLUDE_SIMPLE'])
Return('objs')
