CONFIG_RT_MAIN_THREAD_STACK_SIZE=8192
CONFIG_RT_MAIN_THREAD_PRIORITY=19
CONFIG_RT_USING_MEMHEAP=y
CONFIG_BSP_USING_FULL_ASSERT=y
CONFIG_BSP_USING_PM=y
CONFIG_PM_DEEP_ENABLE=y
# CONFIG_BSP_PM_DEBUG is not set
# CONFIG_GUI_APP_PM is not set
# CONFIG_BLUETOOTH is not set
CONFIG_USING_BUTTON_LIB=y
CONFIG_PKG_USING_LITTLEVGL2RTT=y
CONFIG_LVGL_V9=y
CONFIG_LV_COLOR_DEPTH_16=y
CONFIG_LV_FONT_MONTSERRAT_20=y
CONFIG_LV_FONT_MONTSERRAT_24=y
CONFIG_LV_FONT_DEFAULT_MONTSERRAT_20=y
CONFIG_LV_DEF_REFR_PERIOD=16
CONFIG_LV_FB_LINE_NUM=100
# CONFIG_LV_USE_PERF_MONITOR is not set
# CONFIG_LV_USE_MEM_MONITOR is not set
# CONFIG_LV_USE_SYSMON is not set
