import os
from building import *

cwd = GetCurrentDir()
base64 = os.path.join(cwd, '../../../vendor/SiFli-SDK/external/mbedtls')
objs = DefineGroup('WristFlowProduct', Glob('*.c'), depend=[''],
                   CPPPATH=[cwd, os.path.join(base64, 'include'), os.path.join(cwd, '../../../ui/xml'),
                            os.path.join(cwd, '../../../ui/runtime'), os.path.join(cwd, '../../../core')],
                   CPPDEFINES=['LV_LVGL_H_INCLUDE_SIMPLE'],
                   LOCAL_CCFLAGS=' -Wall -Wextra -Werror=implicit-function-declaration')
objs = objs + DefineGroup('WristFlowWeatherBase64', [os.path.join(base64, 'library/base64.c')], depend=[''],
                    CPPPATH=[cwd, os.path.join(base64, 'include')],
                    LOCAL_CPPDEFINES=[('MBEDTLS_CONFIG_FILE', '\\"weather_base64_config.h\\"')])
Return('objs')
